"""empty message

Revision ID: 2df32a7caae7
Revises: 9dd22a8d729d
Create Date: 2019-01-14 11:09:42.640191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df32a7caae7'
down_revision = '9dd22a8d729d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('timestamp', sa.String(length=32), nullable=True),
    sa.Column('recognized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('drawing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stroke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('glyph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glyph_id'], ['glyph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('stroke_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['stroke_id'], ['stroke.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    op.drop_table('stroke')
    op.drop_table('line')
    op.drop_table('drawing')
    # ### end Alembic commands ###
