"""empty message

Revision ID: e35ed3be8db9
Revises: 
Create Date: 2019-09-23 18:36:25.692190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35ed3be8db9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('timestamp', sa.String(length=32), nullable=True),
    sa.Column('recognized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('font',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=True),
    sa.Column('ascent', sa.Integer(), nullable=True),
    sa.Column('descent', sa.Integer(), nullable=True),
    sa.Column('units_per_em', sa.Integer(), nullable=True),
    sa.Column('xMin', sa.Integer(), nullable=True),
    sa.Column('xMax', sa.Integer(), nullable=True),
    sa.Column('yMin', sa.Integer(), nullable=True),
    sa.Column('yMax', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unicode_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orientation', sa.Boolean(), nullable=True),
    sa.Column('drawing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glyph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unicode', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('advance_width', sa.Integer(), nullable=True),
    sa.Column('left_side_bearing', sa.Integer(), nullable=True),
    sa.Column('xMin', sa.Integer(), nullable=True),
    sa.Column('xMax', sa.Integer(), nullable=True),
    sa.Column('yMin', sa.Integer(), nullable=True),
    sa.Column('yMax', sa.Integer(), nullable=True),
    sa.Column('simple', sa.Boolean(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('font_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['unicode_block.id'], ),
    sa.ForeignKeyConstraint(['font_id'], ['font.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composite',
    sa.Column('glyph_id', sa.Integer(), nullable=True),
    sa.Column('contour_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contour_id'], ['contour.id'], ),
    sa.ForeignKeyConstraint(['glyph_id'], ['glyph.id'], )
    )
    op.create_table('offset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('glyph_name', sa.String(length=64), nullable=True),
    sa.Column('composite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composite_id'], ['glyph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stroke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('contour_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contour_id'], ['contour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('stroke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stroke_id'], ['stroke.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    op.drop_table('stroke')
    op.drop_table('offset')
    op.drop_table('composite')
    op.drop_table('glyph')
    op.drop_table('contour')
    op.drop_table('unicode_block')
    op.drop_table('font')
    op.drop_table('drawing')
    # ### end Alembic commands ###
